spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/chess_db
    username: chess_user
    password: sodlfdmsakfrdma12!
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

server:
  port: 8080
